### ISSUE TITLE
[Suggestion] Show fluids' names on each drawer

### ISSUE THREAD

**Issue by ChromaPIE** [phantamanta44/fluid-drawers#13]
Unlike the items, sometimes it's hard to tell one kind of fluid from another, especially when there are mods providing seas of kinds of them, as the colors could be really alike. It'd be helpful if we can have a feature that displays the name of the fluid each drawer is containing in the overlay.

Anyway, it's ok if it's impossible to be realized.

**Comment by icanhasjonas** [comment]
Hijacking for expanded suggestion,

Once the fluid drawer is locked and has a fluid assigned to it, it would be great if the fluid type label would still be visible. The current behavior is the label disappears when a locked container reaches 0 mb

(Currently playing on MC 1.12.2, maybe this is already fixed in future versions)

**Comment by phantamanta44** [comment]
that sounds like a bug :v
