### ISSUE TITLE
Incompatibility with StackSize Mod when trying to fill a Drawer Tank with stacked Buckets!

### ISSUE THREAD

**Issue by Speecker** [phantamanta44/fluid-drawers#14]
As the title says there seems to be a problem in compatibility with StackSize.

What happened: A Stacked Bucket turns into a single empty one if filling a Drawer Tank by rightclicking it with stacked Buckets in Hand.

Expected behaviour: Remove a single Bucket and place it as en empty one aside leaving the stacked bucket still filled but with 1 bucket count less.

How to Reproduce: Have the Mod "Stacksize" installed. Set Bucket Stacksize to 64. Fill all 64 Buckets with any liquid (for me it was filled with Formic Acid from Erebus). Rightclick an empty Drawer Tank with Stacked Buckets in Hand.

Possibly Helpful Data:
 - Stacksize v1.0
 - FluidDrawers v1.0.5
 - Forge v14.23.5.2854
 - MC: v1.12.2

(pps/offftopic: just for the sake of interest but may it bepossible to make the OG Drawers Show its contents names like the fluid names are shown ?)

Greetings
Speecker

**Comment by phantamanta44** [comment]
fluid drawers just uses forge's generic fluid item handler interface for dealing with fluid transfer, with no special behaviour for buckets in particular. that means this issue is the responsibility of whatever mod is adding stackable buckets; they should have replaced the vanilla bucket fluid handler with one that's designed for stackable buckets

**Comment by Speecker** [comment]
Well Stacksize works on any fluid container as it’s supposed to.
Only on fluid drawers it happens to brake.
